auths/urls.py
from django.conf.urls import include, url
import views 

urlpatterns = [
    url(r'^signin$', views.signin, name='signin'),
    url(r'^signup$', views.signup, name='signup'),
    url(r'^signout$', views.signout, name='signout'),
    url(r'^profile$', views.profile, name='profile'),
]

main/urls.py
from django.conf.urls import include, url
import views 

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^top_ten$', views.top_ten, name='top_ten'),
    url(r'^flop_ten$', views.flop_ten, name='flop_ten'),
    url(r'^last_quotes$', views.last_quotes, name='last_quotes'),
    url(r'^detailed_quote/(?P<quote_id>.+)$', views.detailed_quote, name='detailed_quote'),
]

quote/urls.py
from django.conf.urls import include, url
import views 

urlpatterns = [
    url(r'^create_quote$', views.create_quote, name='create_quote'),
    url(r'^edit_quote/(?P<quote_id>.+)$', views.edit_quote, name='edit_quote'),
    url(r'^delete_quote/(?P<quote_id>.+)$', views.delete_quote, name='delete_quote'),
]

quotegram/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^quote/', include('quote.urls', namespace='quote')),
    url(r'^vote/', include('vote.urls', namespace='vote')),
    url(r'^auths/', include('auths.urls', namespace='auths')),
]

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'%s(?P<path>.*)' % settings.MEDIA_URL[1:], 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

vote/urls.py
from django.conf.urls import include, url
import views 

urlpatterns = [

    url(r'^vote/(?P<quote_id>.+)/(?P<type>.+)$', views.vote, name='vote'),
]

auths/models.py
from django.db import models

# Create your models here.

vote/models.py
# importing django modules
from django.contrib.auth.models import User
from django.db import models
from quote.models import Quote

class Vote(models.Model):
	""" Table to save quotes of users """
	user = models.ForeignKey(User,  verbose_name=' User who votes ')
	quote = models.ForeignKey(Quote,  verbose_name=' Quote of vote ')
	is_upvote = models.BooleanField('is vote positive?', default=True)

	def __unicode__(self):
		return self.user.username +  " ==> " + self.quote.body[:50] + " : " + str(self.is_upvote) 

	class Meta:
		verbose_name = "Vote"
		verbose_name_plural = "Votes"

auths/views.py
# django core packages imports 
from django.shortcuts import redirect, get_object_or_404, render
from django.core.urlresolvers import reverse , reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.conf import settings
# importing project modules 
from custom_code.decorators import logout_required
from quote.models import Quote

@logout_required
def signin(request, key='main'):
	""" SignIn view in order to auhorize users """
	args={}
	if request.GET.get('next', ''):
		messages.info(request, 'You have to be authorized in order to do this action.')

	if request.POST:
		username = request.POST.get('username', '')
		password = request.POST.get('password', '')

		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				# check if we got next value
				next_link = request.POST.get('next', '')
				if next_link != '' :
					return redirect(next_link)
				return redirect(reverse('main:main'))
			else:
				note = ''
				messages.info(request, 'Your account banned.')
		else:
			messages.info(request, 'User name and password missmatch, try again. ')

	template = 'auths/signin.html'
	return render(request, template, {})

@logout_required
def signup(request):
	""" SignUp view in order to auhorize users """
	args={}

	if request.POST:
		username = request.POST.get('username','')
		password = request.POST.get('password','')
		password2 = request.POST.get('password2','')
		# Validation of Username and password
		if User.objects.filter(username=username).exists():
			messages.info(request, 'This username is already used. ')
			return redirect(reverse('auths:signup'))
		if password != password2:
			messages.info(request, 'Passwords are not same.')
			return redirect(reverse('auths:signup'))
		User.objects.create_user(username=username, password=password)
		user_login = authenticate(username=username, password=password)
		login(request, user_login)
		messages.info(request, 'You have successfully Registered. ')
		return redirect(reverse('main:main'))
	template = 'auths/signup.html'
	return render(request, template, {})

@login_required(login_url=reverse_lazy('auths:signin'))
def signout(request):
	""" Signout view """
	logout(request)
	return redirect(reverse("main:main"))

@login_required(login_url=reverse_lazy('auths:signin'))
def profile(request):
	""" Profile view """
	args = {}
	args['quotes'] = Quote.objects.filter(user=request.user).order_by('-id')
	args['profile'] = True
	template = 'auths/profile.html'
	return render(request, template, args)

auths/templates/auths/profile.html
{% extends 'base.html' %}
{%load staticfiles%}
{% block navigation %}
	<li><a href="{% url 'main:top_ten' %}">TOP 10</a></li>
	<li><a href="{% url 'main:flop_ten' %}">FLOP 1O </a></li>
	<li><a href="{% url 'main:last_quotes' %}">LAST</a></li>
{% endblock %}
{% block content %}
	<div id="blue">
		<div class="container">
			<div class="row centered">
				<h4>Profile</h4>
			</div><!-- row -->
		</div><!-- container -->
	</div><!-- blue wrap -->


	<div class="container w">
		<div class="row centered">
			<br><br>
			{% for quote in quotes %}
				<div class="col-md-8 col-md-offset-2 well">
					<span style="display: inline-block;"><p class="text-left">random #{{forloop.counter}} quote of 10 : {{quote.count_vote}} Score
					<a class="btn btn-sm btn-primary" data-toggle="collapse" data-target="#detailed_vote{{quote.pk}}" aria-expanded="false" aria-controls="detailed_vote{{quote.pk}}">Detail</a>
					</p></span>
					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

					<span class="text-right"><p style="display: inline-block;"><a href="{% url 'quote:edit_quote' quote.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></i></a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href="{% url 'quote:delete_quote' quote.id %}"><i class="fa fa-times"></i></a></p></span>

					<div class="collapse" id="detailed_vote{{quote.pk}}">
					  <div class="well">
					    {% for vote in quote.vote_set.all %}
					    	{% if vote.is_upvote %}
					    		<p class="text-left" style="color:green">upvote : {{ vote.user.username }}</p>
					    	{% else %}
					    		<p class="text-right" style="color:red">downvote : {{ vote.user.username }}</p>
					    	{% endif %}
					    {% endfor %}
					  </div>
					</div>
					<a href="{% url 'main:detailed_quote' quote.id %}">
						<h4>"{{quote.body|slice:"20"}}..."</h4>
						<p>- {{quote.user.username}}</p>
					</a>
					<p class="text-right"><a href="{% url 'vote:vote' quote.id 1 %}"><i class="fa fa-thumbs-up"></a></i>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href="{% url 'vote:vote' quote.id 0 %}"><i class="fa fa-thumbs-down"></i></a></p>
				</div><!-- col-lg-4 -->
			{% empty %}
				<h1>You have no quote yet.</h1>
				<br><br><br><br>
			{% endfor %}
		</div><!-- row -->
	</div><!-- container -->
{% endblock %}	
	

auths/templates/auths/signin.html
{% extends 'base.html' %}
{%load staticfiles%}
{% block navigation %}
	<li><a href="{% url 'main:top_ten' %}">TOP 10</a></li>
	<li><a href="{% url 'main:flop_ten' %}">FLOP 1O </a></li>
	<li><a href="{% url 'main:last_quotes' %}">LAST</a></li>
{% endblock %}
{% block content %}
	<div id="headerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-4 col-lg-offset-4" style="margin-top: 70px">
					<h2 style="color:white"> SignIn </h2>
					<form action="" method="POST" role="form" >
						{% csrf_token %}
						<input type="text" name="username" placeholder="Enter username here " required="" class="form-control">
						<br>
						<input type="password" name="password" placeholder="Enter password here " required="" class="form-control">
						<br>
						<button class="btn btn-success form-control" type="submit">SignIn</button>
					</form>
					<h5 style="color:white">or</h5>
					<a href="{% url 'auths:signup' %}"><button class="btn btn-primary form-control" type="submit">SignUp</button></a>
				</div>

				
				</div>
			</div>
		</div>
	</div>
{% endblock %}	
	

auths/templates/auths/signup.html
{% extends 'base.html' %}
{%load staticfiles%}
{% block navigation %}
	<li><a href="{% url 'main:top_ten' %}">TOP 10</a></li>
	<li><a href="{% url 'main:flop_ten' %}">FLOP 1O </a></li>
	<li><a href="{% url 'main:last_quotes' %}">LAST</a></li>
{% endblock %}
{% block content %}
	<div id="headerwrap">
		<div class="container">
			<div class="row centered">
				<div class="col-lg-4 col-lg-offset-4" style="margin-top: 70px">
					<h2 style="color:white"> SignUp </h2>
					<form action="" method="POST" role="form" >
						{% csrf_token %}
						<input type="text" name="username" placeholder="Enter username here " required="" class="form-control">
						<br>
						<input type="password" name="password" placeholder="Enter password here " required="" class="form-control">
						<br>
						<input type="password" name="password2" placeholder="Repeat password here " required="" class="form-control"><br>
						<button class="btn btn-success form-control" type="submit">SignUp</button>
						
					</form>
					<h5 style="color:white">or</h5>
					<a href="{% url 'auths:signin' %}"><button class="btn btn-primary form-control" type="submit">SignIn</button></a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}	
	