auths/urls.py
from django.conf.urls import include, url
import views 

urlpatterns = [
    url(r'^signin$', views.signin, name='signin'),
    url(r'^signup$', views.signup, name='signup'),
    url(r'^signout$', views.signout, name='signout'),
    url(r'^profile$', views.profile, name='profile'),
]

main/urls.py
from django.conf.urls import include, url
import views 

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^top_ten$', views.top_ten, name='top_ten'),
    url(r'^flop_ten$', views.flop_ten, name='flop_ten'),
    url(r'^last_quotes$', views.last_quotes, name='last_quotes'),
    url(r'^detailed_quote/(?P<quote_id>.+)$', views.detailed_quote, name='detailed_quote'),
]

quote/urls.py
from django.conf.urls import include, url
import views 

urlpatterns = [
    url(r'^create_quote$', views.create_quote, name='create_quote'),
    url(r'^edit_quote/(?P<quote_id>.+)$', views.edit_quote, name='edit_quote'),
    url(r'^delete_quote/(?P<quote_id>.+)$', views.delete_quote, name='delete_quote'),
]

quotegram/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^quote/', include('quote.urls', namespace='quote')),
    url(r'^vote/', include('vote.urls', namespace='vote')),
    url(r'^auths/', include('auths.urls', namespace='auths')),
]

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'%s(?P<path>.*)' % settings.MEDIA_URL[1:], 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

main/forms.py
from django import forms
from django.forms.utils import ErrorList

main/views.py
from django.shortcuts import render,get_object_or_404 ,redirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from quote.models import Quote

def main(request):
	""" Main page view """
	args = {}
	quotes = Quote.objects.all()
	args['quotes'] = quotes.order_by('?')[:10]
	template = 'main/index.html'
	return render(request, template, args)

def detailed_quote(request, quote_id):
	""" Main page view """
	args = {}
	args['quote'] = get_object_or_404(Quote, pk=quote_id)
	template = 'main/detailed_quote.html'
	return render(request, template, args)

def top_ten(request):
	""" Top ten votes view """
	args = {}
	quotes = Quote.objects.all()
	args['random_quote'] = quotes.order_by('?')[0]
	args['quotes'] = quotes.order_by('-count_vote')[:10]
	template = 'main/top_ten.html'
	return render(request, template, args)

def flop_ten(request):
	""" Flop ten votes view """
	args = {}
	quotes = Quote.objects.all()
	args['random_quote'] = quotes.order_by('?')[0]
	args['quotes'] = quotes.order_by('count_vote')[:10]
	template = 'main/flop_ten.html'
	return render(request, template, args)

def last_quotes(request):
	""" Flop ten votes view """
	args = {}
	quotes = Quote.objects.all()
	args['random_quote'] = quotes.order_by('?')[0]
	args['quotes'] = quotes.order_by('-count_vote')
	template = 'main/last_quotes.html'
	return render(request, template, args)

main/templates/base.html
{% load staticfiles %} 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/ico/favicon.png">

    <title>QUOTEGRAM - TECH TASK</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'main:main' %}">QU<i class="fa fa-circle"></i>TEGRAM</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% block navigation %}
            {% endblock %}
            {% if user.is_authenticated %}
              {% if profile == True %}
                <li class="active"><a href="{% url 'auths:profile' %}">{{request.user.username|upper}}</a></li>
              {% else %}
                <li><a href="{% url 'auths:profile' %}">{{request.user.username|upper}}</a></li>
              {% endif %}
              <li><a data-toggle="modal" data-target="#signOutModal" href="#signOutModal">SIGNOUT</a></li>
            {% else %}
              <li><a href="{% url 'auths:signin' %}">SIGNIN</a></li>
              <li><a href="{% url 'auths:signup' %}">SIGNUP</a></li>
            {% endif %}
            <li><a href="{% url 'quote:create_quote' %}"><i class="fa fa-pencil-square-o"></i></a></li>
          </ul>
        </div>
      </div>
    </div>

    {% if messages %} <br>{% for message in messages %} {% if message.tags == 'error' %}
      <div class="alert alert-danger fade in text-center">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <h4 style="font-family: 'museo', 'museo', Arial, sans-serif;">{{message}}</h4>
      </div>
    {% else %}
      <div class="alert alert-{{message.tags}} fade in text-center">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <h4 style="font-family: 'museo', 'museo', Arial, sans-serif;">{{message}}</h4>
      </div>
    {% endif %} {% endfor %} {% endif %}

    {% block content %}
    {% endblock %}
   <!-- FOOTER -->
    <div id="f">
        <div class="container">
            <div class="row centered">
                <a href="https://github.com/ArietNyshanbaev/quotegram"><i class="fa fa-github"></i></a>
            </div><!-- row -->
        </div><!-- container -->
    </div><!-- Footer -->


    <!-- MODAL FOR CONTACT -->
    <!-- Modal -->
    <div class="modal fade" id="signOutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Sign Out</h4>
          </div>
          <div class="modal-body">
            <div class="row centered">
                <h5>Already want to leave us?</h5>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <a href="{% url 'auths:signout' %}"><button type="button" class="btn btn-danger">Leave</button></a>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->


    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>